version: '3'

services:
  eureka:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8761:8761'
      working_dir: /eureka-server
      volumes:
        - ./eureka-server:/eureka-server
      command: './gradlew bootRun'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev

  api-gateway:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8080:8080'
      working_dir: /api-gateway
      volumes:
        - ./api-gateway:/api-gateway
      depends_on:
        - eureka
      command: './gradlew bootRun'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev

  favs-api:
        image: anapsix/alpine-java:8_jdk_unlimited
        ports:
          - '8081:8081'
        working_dir: /favs-api
        volumes:
          - ./favs-api:/favs-api
        depends_on:
          - postgresdev
        command: './gradlew bootRun'
        environment:
          - GRADLE_USER_HOME=cache
          - SPRING_PROFILES_ACTIVE=dev

#  nyc-records-search:
#        image: node:latest
#        build: ./nyc-records-search
#        ports:
#          - 3000:3000
#        working_dir: /nyc-records-search
#        volumes:
#          - ./nyc-records-search:/nyc-records-search
#        command: 'yarn start'
#        depends_on:
#          - eureka
#          - postgresdev
#          - favs-api

  postgresdev:
      image: postgres
      ports:
       - "5432:5432"
      environment:
       - POSTGRES_PASSWORD=password
       - POSTGRES_USER=postgres
       - POSTGRES_DB=pgdev
